runtime: python27
api_version: 1
threadsafe: true

instance_class: F1
automatic_scaling:
  min_idle_instances: 0
  max_idle_instances: 1
  min_pending_latency: 50ms
  max_pending_latency: 300ms
  max_concurrent_requests: 8

builtins:
- deferred: on
- remote_api: on

inbound_services:
  - warmup

libraries:
- name: jinja2
  version: "2.6"
- name: webapp2
  version: "2.5.2"

skip_files:
- ^\.
- ^.*\.md$
- ^.*\.py[co]$

handlers:
- url: /
  script: main.app
